### ISSUE TITLE
CSI - are you sure?

### ISSUE THREAD

**Issue by ana-oprescu** [software-engineering-amsterdam/ST-2016-wo1-5#1]
I see your team has spent a lot of time on this exercise. Perhaps double-check your answer?
good luck!
Ana

**Comment by Chronophobe** [comment]
I think that depends on how you interpret the question. I will try to explain how I went about solving the problem:

My first thought was that if person A is lying, then the inverse of his statement is the truth. So if Matthew accuses Jack, then if Matthew is lying he accuses everyone except Jack. 

With that in mind we can navigate the solution space by checking every permutation of truth-tellers and liers (thus, with the inverse statements of the liers). Then a solution exists iff one person is accused by everyone. 

I think this might essentially be the same as checking when one person is accused by at least three people (thus ignoring the statements of potential liers). 

The problem with my solution (and probably the other one too) is that if you check for consensus in a different order you might find a different solution as there are multiple. (I found this to be true if I changed the order of the `honestyMapping` before calculating its permutations).

**Comment by Chronophobe** [comment]
For completeness: 

After the discussion with Ana about the problem and my solution, I more or less understand it. 
The only three people who can tell the truth are those three (or the smallest(?) majority in general) that do not contradict each other (related problem: Byzantine fault). 

Now I still think my original thoughts were right (and synonymous to the proper solution). However upon double checking the outcome (i.e. checking who the honest boys agree on), it doesn't come up with `Matthew`. (in fact, there is no consensus at all). Ergo, I made a mistake somewhere (probably because I was thinking this problem was way more complex than it is).

Either way, I'm happy I understand the problem better now. So, thank you for the clarification, Ana!

Thanks for the clarification, Ana!
